"""Add color and size to CartItem

Revision ID: 207825390548
Revises: 
Create Date: 2024-09-13 16:45:54.169616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207825390548'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('color', sa.String(), nullable=False))
    op.add_column('cart_items', sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='size'), nullable=False))
    op.add_column('order_items', sa.Column('color', sa.String(), nullable=False))
    op.add_column('order_items', sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='size'), nullable=False))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CREATED', 'PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               existing_nullable=True)
    op.drop_index('ix_products_cart_id', table_name='products')
    op.drop_constraint('products_cart_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'cart_id')
    op.add_column('sales', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales', 'orders', ['order_id'], ['id'])
    op.add_column('wishlist_items', sa.Column('color', sa.String(), nullable=False))
    op.add_column('wishlist_items', sa.Column('size', sa.Enum('XS', 'S', 'M', 'L', 'XL', 'XXL', name='size'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_items', 'size')
    op.drop_column('wishlist_items', 'color')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'order_id')
    op.add_column('products', sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('products_cart_id_fkey', 'products', 'cart', ['cart_id'], ['id'])
    op.create_index('ix_products_cart_id', 'products', ['cart_id'], unique=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('CREATED', 'PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('order_items', 'size')
    op.drop_column('order_items', 'color')
    op.drop_column('cart_items', 'size')
    op.drop_column('cart_items', 'color')
    # ### end Alembic commands ###
